carts/urls.py
from django import views
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('',views.cart_view,name='cart_view'),
    path('add-to-cart/',views.cart_add_product,name='add_to_cart_one'),
    path('add-to-cart-detail/', views.cart_add_product_from_detail,
         name='cart_add_product_from_detail'),
    path('update-cart-qty/',views.update_cart,name='update_cart'),
    path('delete-cart-qty/', views.delete_cart_item, name='delete_cart_item'),
    path('placeorder/', views.place_order_cart, name='place_order_cart'),
    path('checkoutcart/', views.checkout_cart, name='checkout_cart'),
 
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('',include('stores.urls',namespace='stores')),
    path('account/',include('users.urls',namespace='users')),
    path('profile/',include('profiles.urls',namespace='profiles')),
    path('carts/',include('carts.urls',namespace='carts')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path
from . import views

app_name='profiles'
urlpatterns = [
    path('',views.profile_index,name='profile_index'),
]

stores/urls.py
from django.urls import path
from . import views

app_name = 'stores'
urlpatterns = [
    path('',views.store_home,name='store_home'),
    path('shopping/', views.store_shopping, name='store_shopping'),
    path('shopping/<slug:slug_cate>/', views.store_category_product,name='store_category_product'),
    path('product/<slug:pro_slug>/', views.store_product_details,name='product_detail'),
    path('product/sub/<slug:cat_slug>/',views.store_sub_menu_product, name='store_sub_menu_product'),
    path('search/', views.product_search, name='product_search')
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from . import views

app_name = 'users'

urlpatterns = [
    path('register/',views.account_register,name='account_register'),
    path('activate-account/<uidb64>/<token>/',views.account_activte,name='activate'),
    path('login/',views.account_login,name='account_login'),
    path('logout/',views.account_logout,name='account_logout'),

    # reset password
    path('password_reset/',auth_view.PasswordResetView.as_view(
                                                                template_name='users/reset/password_reset.html',
                                                                email_template_name='users/reset/email_reset.html',
                                                                success_url='/account/password_reset_done'),
                                                                name='password_reset'),
    path('password_reset_done/',auth_view.PasswordResetDoneView.as_view(
                                                                        template_name='users/reset/password_reset_done.html'),
                                                                        name='password_reset_done'),

    path('password_reset_confirm/<uidb64>/<token>/',auth_view.PasswordResetConfirmView.as_view(
                                                                    template_name='users/reset/password_reset_confirm.html',
                                                                    success_url='/account/password_reset_complete'),name='password_reset_confirm'),
    path('password_reset_complete/',auth_view.PasswordResetCompleteView.as_view(template_name='users/reset/password_reset_complete.html'),
                                                                                name='password_reset_complete'),                                                                                                                          
    path('user_contact/', views.users_contact, name='users_contact'),
]

stores/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model

from profiles.models import Profile

User = get_user_model()

# Create your models here.


class Category(models.Model):
    slug = models.SlugField(max_length=200, unique=True,
                            null=False, blank=False)
    name = models.CharField(max_length=200, unique=True,
                            null=False, blank=False)
    category_image = models.ImageField(
        upload_to='category', null=True, blank=True)

    def __str__(self):
        return self.name

    def delete(self, *args, **kwargs):
        self.category_image.delete()
        return super().delete(*args, **kwargs)


class Carousel(models.Model):
    carousel_image1 = models.ImageField(upload_to='carousel')
    carousel_image2 = models.ImageField(upload_to='carousel')

    def delete(self, *args, **kwargs):
        self.carousel_image.delete()
        return super().delete(*args, **kwargs)


class SubCategory(models.Model):
    sub_category = models.ManyToManyField(Category)
    slug = models.SlugField(max_length=200, null=False, blank=False)
    name = models.CharField(max_length=200, null=False, blank=False)

    def __str__(self):
        return self.name


class SizeProduct (models.Model):
    slug = models.SlugField(max_length=200, null=False, blank=False)
    name = models.CharField(max_length=200, null=False, blank=False)
    
    def __str__(self):
        return self.name


class ColorProduct (models.Model):
    slug = models.SlugField(max_length=200, null=False, blank=False)
    name = models.CharField(max_length=200, null=False, blank=False)
    


    def __str__(self):
        return self.name



class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=200, unique=True,
                            null=False, blank=True)
    name = models.CharField(max_length=200, unique=True,
                            null=False, blank=False)
    color = models.CharField(max_length=200)
                            
    product_image = models.ImageField(
        upload_to='product', null=False, blank=False)
    product_img1 = models.ImageField(
        upload_to='product/sub', null=True, blank=True)
    product_img2 = models.ImageField(
        upload_to='product/sub', null=True, blank=True)
    product_img3 = models.ImageField(
        upload_to='product/sub', null=True, blank=True)
    product_quantity = models.IntegerField()
    current_price = models.FloatField()
    selling_price = models.FloatField()
    small_description = models.TextField(
        max_length=500, null=False, blank=False)
    description = models.TextField(null=False, blank=False)
    information = models.TextField(max_length=500, null=False, blank=False)
    product_size = models.ManyToManyField(
        SizeProduct, related_name='product_size')
    product_color = models.ManyToManyField(
        ColorProduct, related_name='product_color')
    

    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def delete(self, *args, **kwargs):
        self.product_image.delete()
        self.product_img1.delete()
        self.product_img2.delete()
        self.product_img3.delete()
        return super().delete(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("stores:product_search", args=[self.name])


class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    review = models.CharField(max_length=250)
    create_at = models.DateTimeField(auto_now_add=True)
    rating = models.FloatField()
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.review

stores/views.py
from django.contrib import messages
from django.core.paginator import PageNotAnInteger, EmptyPage, Paginator
from django.shortcuts import get_object_or_404, redirect, render
from .models import Carousel, Category, ColorProduct, Product, SizeProduct, SubCategory, Review
from django.contrib.auth import get_user_model


User = get_user_model()

# Create your views here.


def store_home(request):
    carousel = Carousel.objects.filter().first()
    category = Category.objects.all()
    context = {
        'carousel': carousel,
        'category': category,

    }
    return render(request, 'stores/index.html', context)


def store_shopping(request):
    products = Product.objects.all().order_by('?')
    paginator = Paginator(products, 6)
    page = request.GET.get('page')
    try:
        page = paginator.page(page)
    except PageNotAnInteger:
        page = paginator.page(1)
    except EmptyPage:
        page = paginator.page(paginator.num_pages)
    context = {
        'products': page,

    }
    return render(request, 'stores/shope.html', context)


def store_category_product(request, slug_cate):
    category = get_object_or_404(Category, slug=slug_cate)
    print(category)
    products = Product.objects.filter(category=category).order_by('?')
    paginator = Paginator(products, 6)
    page = request.GET.get('page')
    try:
        page = paginator.page(page)
    except PageNotAnInteger:
        page = paginator.page(1)
    except EmptyPage:
        page = paginator.page(paginator.num_pages)
    context = {
        'products': page,
        'cat': category,

    }
    return render(request, 'stores/shopping_cate.html', context)


def store_product_details(request, pro_slug):

    product = get_object_or_404(Product, slug=pro_slug)
    products = Product.objects.filter(category=product.category).exclude(
        name=product.name).order_by('?')
    reviews = Review.objects.filter(product=product)
    paginator = Paginator(reviews, 2)
    page = request.GET.get('page')
    try:
        page = paginator.page(page)
    except PageNotAnInteger:
        page = paginator.page(1)
    except EmptyPage:
        page = paginator.page(paginator.num_pages)

    product = Product.objects.get(slug=pro_slug)
    author = request.user
    if request.method == 'POST':
        url = request.META.get('HTTP_REFERER')
        review = request.POST.get('review')
        rating_view = request.POST.get('rating')
        if author.is_authenticated:
            if Review.objects.filter(product=product, author=author).first():
                messages.error(
                    request, ' You Already Have a Reviews on This Product ')
                return redirect(url)
            if rating_view and review:
                rev = Review(
                    product=product,
                    review=review,
                    author=author,
                    rating=rating_view,
                )
                rev.save()
                review = ''
                rating_view = ''
                messages.success(request, 'Thank You ')

            else:
                messages.error(request, ' Please Rate and Text To Reviews ')
        else:
            messages.success(request, 'you must logged in')
            return redirect(url)

    all_review_count = Review.objects.filter(product=product).count()
    size = SizeProduct.objects.all()
    context = {
        'product': product,
        'products': products,
        'reviews': page,
        'all_review_count': all_review_count,
        'size':size

    }
    return render(request, 'stores/product_detail.html', context)


def store_sub_menu_product(request, cat_slug):
    sub_categorey = get_object_or_404(SubCategory, slug=cat_slug)
    product = Product.objects.filter(subcategory=sub_categorey).order_by('?')
    paginator = Paginator(product, 6)
    page = request.GET.get('page')
    try:
        page = paginator.page(page)
    except PageNotAnInteger:
        page = paginator.page(1)
    except EmptyPage:
        page = paginator.page(paginator.num_pages)
    context = {
        'products': page,
        'sub_cat': sub_categorey
    }
    return render(request, 'stores/sub_menu_product.html', context)


def product_search(request):
    search = request.GET.get('search_store')
    search_pro = Product.objects.filter(name__icontains=search)
    paginator = Paginator(search_pro, 6)
    page = request.GET.get('page')
    try:
        page = paginator.page(page)
    except PageNotAnInteger:
        page = paginator.page(1)
    except EmptyPage:
        page = paginator.page(paginator.num_pages)
    context = {'search_pro': page, 'search': search}
    return render(request, 'stores/search_results.html', context)

stores/templates/stores/index.html
{% extends '_base.html' %}

{% block carousel %}
<style>
   .img{
    width:100%;
    height:200px; 
   }
</style>
    <div class="container-fluid">
        <div class="row border-top px-xl-5">
            <div class="col-lg-3 d-none d-lg-block">
                <a class="btn shadow-none d-flex align-items-center justify-content-between bg-primary text-white w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; margin-top: -1px; padding: 0 30px;">
                    <h6 class="m-0">Categories</h6>
                    <i class="fa fa-angle-down text-dark"></i>
                </a>
                <nav class="collapse show navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0" id="navbar-vertical">
                    <div class="navbar-nav w-100 overflow-hidden" style="height: 410px">
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link" data-toggle="dropdown">Dresses <i class="fa fa-angle-down float-right mt-1"></i></a>
                            <div class="dropdown-menu position-absolute bg-secondary border-0 rounded-0 w-100 m-0">
                                {% for cate in category_context %}
                                <a href="{% url 'stores:store_category_product' cate.slug %}" class="dropdown-item">{{cate.name|capfirst}}</a>
                                {% endfor %}
                            </div>
                        </div>
                        {% for sub in subcategory_context %}
                        <a href="{% url 'stores:store_sub_menu_product' sub.slug %}" class="nav-item nav-link">{{sub|capfirst}}</a>
                        {% endfor %}
                    </div>
                </nav>
            </div>
            <div class="col-lg-9">
                <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
                    <a href="" class="text-decoration-none d-block d-lg-none">
                        <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">E</span>Shopper</h1>
                    </a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav mr-auto py-0">
                            <a href=" {% url 'stores:store_home' %}" class="nav-item nav-link active">Home</a>
                            <a href="{% url 'stores:store_shopping' %}" class="nav-item nav-link ">Shop</a>
                            <a href="" class="nav-item nav-link">About Us</a>
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Pages</a>
                                <div class="dropdown-menu rounded-0 m-0">
                                    <a href="{% url 'carts:cart_view' %}" class="dropdown-item">Shopping Cart</a>
                                    <a href="{% url 'carts:place_order_cart' %}" class="dropdown-item">Checkout</a>
                                </div>
                            </div>
                            <a href="{% url 'users:users_contact' %}" class="nav-item nav-link">Contact</a>
                        </div>
                        <div class="navbar-nav ml-auto py-0">
                            {% if request.user.is_authenticated %}
                            <a href="{% url 'profiles:profile_index' %}" class="nav-item nav-link">Profile</a>
                            <a href="{% url 'users:account_logout' %}" class="nav-item nav-link">Logout</a>
                            {% else %}
                            <a href="{% url 'users:account_login' %}" class="nav-item nav-link">Login</a>
                            <a href="{% url 'users:account_register' %}" class="nav-item nav-link">Register</a>
                            {% endif %}
                        </div>
                    </div>
                </nav>
                <div id="header-carousel" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active" style="height: 410px;">
                            <img class="img-fluid" src="{{carousel.carousel_image1.url}}" alt="Image">
                            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                                <div class="p-3" style="max-width: 700px;">
                                    <h4 class="text-light text-uppercase font-weight-medium mb-3">10% Off Your First Order</h4>
                                    <h3 class="display-4 text-white font-weight-semi-bold mb-4">Fashionable Dress</h3>
                                    <a href="{% url 'stores:store_shopping' %}" class="btn btn-light py-2 px-3">Shop Now</a>
                                </div>
                            </div>
                        </div>
                        <div class="carousel-item" style="height: 410px;">
                            <img class="img-fluid" src="{{carousel.carousel_image2.url}}" alt="Image">
                            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                                <div class="p-3" style="max-width: 700px;">
                                    <h4 class="text-light text-uppercase font-weight-medium mb-3">10% Off Your First Order</h4>
                                    <h3 class="display-4 text-white font-weight-semi-bold mb-4">Reasonable Price</h3>
                                    <a href="{% url 'stores:store_shopping' %}" class="btn btn-light py-2 px-3">Shop Now</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#header-carousel" data-slide="prev">
                        <div class="btn btn-dark" style="width: 45px; height: 45px;">
                            <span class="carousel-control-prev-icon mb-n2"></span>
                        </div>
                    </a>
                    <a class="carousel-control-next" href="#header-carousel" data-slide="next">
                        <div class="btn btn-dark" style="width: 45px; height: 45px;">
                            <span class="carousel-control-next-icon mb-n2"></span>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!-- Navbar End -->


{% endblock carousel %}




{% block category %}
  <!-- Categories Start -->

  <!-- Categories End -->
{% endblock category %}



{% block featured %}
        <!-- Featured Start -->
 
    <div class="container-fluid pt-5">
        <div class="row px-xl-5 pb-3">
            <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
                <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
                    <h1 class="fa fa-check text-primary m-0 mr-3"></h1>
                    <h5 class="font-weight-semi-bold m-0">Quality Product</h5>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
                <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
                    <h1 class="fa fa-shipping-fast text-primary m-0 mr-2"></h1>
                    <h5 class="font-weight-semi-bold m-0">Free Shipping</h5>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
                <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
                    <h1 class="fas fa-exchange-alt text-primary m-0 mr-3"></h1>
                    <h5 class="font-weight-semi-bold m-0">14-Day Return</h5>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
                <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
                    <h1 class="fa fa-phone-volume text-primary m-0 mr-3"></h1>
                    <h5 class="font-weight-semi-bold m-0">24/7 Support</h5>
                </div>
            </div>
        </div>
    </div>
    <!-- Featured End -->
{% endblock featured %}


{% block product_index %}
        <!-- product_index Start -->
    <div class="container-fluid pt-5">
        <div class="row px-xl-5 pb-3">
            {% for category in category %}
            <div class="col-lg-4 col-md-6 pb-1">
                <div class="cat-item d-flex flex-column border mb-4" style="padding: 30px;">
                    <a href="{% url 'stores:store_category_product' category.slug %}" class="cat-img position-relative overflow-hidden mb-3">
                        <img class="img-fluid img" src="{{category.category_image.url}}" alt="">
                    </a>
                    <h5 class="font-weight-semi-bold m-0">{{category.name}}</h5>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <!-- product_index End -->
{% endblock product_index %}

stores/templates/stores/search_results.html
{% extends '_base.html' %}
{% block carousel %}
<style>
    .img-shope{
        width: 432px;
        height:432px;
    }
</style>
{% include 'includes/navbar.html' %}
     <!-- Page Header Start -->
    <div class="container-fluid bg-secondary mb-5">
        <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
            <h1 class="font-weight-semi-bold text-uppercase mb-3">All Products</h1>
            <div class="d-inline-flex">
                <p class="m-0"><a href="{% url 'stores:store_home' %}">Home</a></p>
                <p class="m-0 px-2">-</p>
                <p class="m-0">Search Result For (<a href="">{{search }}</a>)</p>
            </div>
        </div>
    </div>
    <!-- Page Header End -->

    <div class="row px-xl-5">
       
        <!-- Shop Product Start -->
        {% if  search_pro %}
            {% for product in search_pro %}
                <div class="col-lg-4 col-md-6 col-sm-12 pb-1">
                    <div class="card product-item border-0 mb-4">
                        <div
                            class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                            <img class="img-fluid w-100 img-shope" src="{{product.product_image.url}}" alt="">
                        </div>
                        <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                            <h6 class="text-truncate mb-3">{{product.name|capfirst}}</h6>
                            <div class="d-flex justify-content-center">
                                {% if product.current_price > 0 %}
                                <h6 class="text-muted ml-2"><del>${{product.current_price}}</del></h6>
                                <h6>${{product.selling_price}}</h6>
                                {% endif %}
                                
                            </div>
                        </div>
                        <div class="card-footer d-flex justify-content-between bg-light border">
                            <a href="{% url 'stores:product_detail' product.slug %}" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>View
                                Detail</a>
                            <a href="" class="btn btn-sm text-dark p-0"><i
                                    class="fas fa-shopping-cart text-primary mr-1"></i>Add To Cart</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% else %}
            <h2>Product Not Found</h2>
            {% endif %}    
               
                <div class="col-12 pb-1">
            <div class="col-12 pb-1">
                        <nav aria-label="Page navigation">
                          <ul class="pagination justify-content-center mb-3">
                              {% with search_pro as page %}
                              {% if page.has_previous %}
                            <li class="page-item active">
                              <a class="page-link" href="?page={{page.previous_page_number}}">
                                <span aria-hidden="true">&laquo;</span>
                                <span class="sr-only">Previous</span>
                              </a>
                            </li>
                            {% endif %}
                            {% if page.has_other_pages %}
                            <span class="page-item ">
                                <li class="page-item d-flex">
                                   <a class="page-link" href=""> {{ page.number }}</a>
                                   <a class="page-link" href=""> {{ page.paginator.num_pages }} </a>
                                </li>            
                            </span>
                            {% else %}
                            <span class="page-item">
                                <li class="page-item d-flex">
                                   <a class="page-link" href=""> {{ page.number }}</a>
                                </li>            
                            </span>
                            {% endif %}
                            {% if page.has_next %}
                            <li class="page-item active">
                              <a class="page-link" href="?page={{page.next_page_number}}">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span>
                              </a>
                            </li>
                             {% endif %}
                            {% endwith %}
                          </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Shop Product End -->
{% endblock carousel %}

stores/templates/stores/shope.html
{% extends '_base.html' %}
{% load static %}
{% block carousel %}
<style>
    .img-shope {
        width: 432px;
        height: 432px;
    }
</style>
{% include 'includes/navbar.html' %}
<!-- Page Header Start -->
<div class="container-fluid bg-secondary mb-5">
    <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
        <h1 class="font-weight-semi-bold text-uppercase mb-3">All Products</h1>
        <div class="d-inline-flex">
            <p class="m-0"><a href="{% url 'stores:store_home' %}">Home</a></p>
            <p class="m-0 px-2">-</p>
            <p class="m-0">shop</p>
        </div>
    </div>
</div>
<!-- Page Header End -->

<div class="row px-xl-5 ">

    <!-- Shop Product Start -->
    {% for product in products %}
    <div class="col-lg-4 col-md-6 col-sm-12 pb-1 product-data">
        <form action="" method="post">
            <div class="card product-item border-0 mb-4 ">
                {% csrf_token %}
                <input type="hidden" name="" class="product-id" value="{{product.id}}">
                <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                    <img class="img-fluid w-100 img-shope" src="{{product.product_image.url}}" alt="">
                </div>
                <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                    <h6 class="text-truncate mb-3">{{product.name|capfirst}}</h6>
                    <div class="d-flex justify-content-center">
                        {% if product.current_price > 0 %}
                        <h6 class="text-muted ml-2"><del>${{product.current_price}}</del></h6>
                        <h6>${{product.selling_price}}</h6>
                        {% endif %}
                    </div>
                </div>
                <div class="card-footer d-flex justify-content-between bg-light border">
                    <a href="{% url 'stores:product_detail' product.slug %}" class="btn btn-sm text-dark p-0"><i
                            class="fas fa-eye text-primary mr-1"></i>View
                        Detail</a>
                    <a href="" class="btn btn-sm text-dark p-0 add-to-cart" type="button" role="button"><i
                    class="fas fa-shopping-cart text-primary mr-1"></i>Add To Cart</a>
                </div>
            </div>
        </form>
    </div>
    {% endfor %}

    <div class="col-12 pb-1">
        <div class="col-12 pb-1">
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center mb-3">
                    {% with products as page %}
                    {% if page.has_previous %}
                    <li class="page-item active">
                        <a class="page-link" href="?page={{page.previous_page_number}}">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                    {% endif %}
                    {% if page.has_other_pages %}
                    <span class="page-item ">
                        <li class="page-item d-flex">
                            <a class="page-link" href=""> {{ page.number }}</a>
                            <a class="page-link" href=""> {{ page.paginator.num_pages }} </a>
                        </li>
                    </span>
                    {% else %}
                    <span class="page-item">
                        <li class="page-item d-flex">

                        </li>
                    </span>
                    {% endif %}
                    {% if page.has_next %}
                    <li class="page-item active">
                        <a class="page-link" href="?page={{page.next_page_number}}">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                    {% endif %}
                    {% endwith %}
                </ul>
            </nav>
        </div>
    </div>
</div>
</div>
</div>
</div>
<!-- Shop Product End -->

   <script src="{% static 'js/cart.js' %}"></script>

{% endblock carousel %}