carts/urls.py
from django import views
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('',views.cart_view,name='cart_view'),
    path('add-to-cart/',views.cart_add_product,name='add_to_cart_one'),
    path('add-to-cart-detail/', views.cart_add_product_from_detail,
         name='cart_add_product_from_detail'),
    path('update-cart-qty/',views.update_cart,name='update_cart'),
    path('delete-cart-qty/', views.delete_cart_item, name='delete_cart_item'),
    path('placeorder/', views.place_order_cart, name='place_order_cart'),
    path('checkoutcart/', views.checkout_cart, name='checkout_cart'),
 
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('',include('stores.urls',namespace='stores')),
    path('account/',include('users.urls',namespace='users')),
    path('profile/',include('profiles.urls',namespace='profiles')),
    path('carts/',include('carts.urls',namespace='carts')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

stores/urls.py
from django.urls import path
from . import views

app_name = 'stores'
urlpatterns = [
    path('',views.store_home,name='store_home'),
    path('shopping/', views.store_shopping, name='store_shopping'),
    path('shopping/<slug:slug_cate>/', views.store_category_product,name='store_category_product'),
    path('product/<slug:pro_slug>/', views.store_product_details,name='product_detail'),
    path('product/sub/<slug:cat_slug>/',views.store_sub_menu_product, name='store_sub_menu_product'),
    path('search/', views.product_search, name='product_search')
]

carts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from stores.models import Product


# Create your models here.

User = get_user_model()


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=150, null=False, blank=False)
    address = models.TextField(null=False, blank=False)
    address2 = models.TextField(null=False, blank=False)
    city = models.CharField(max_length=150, null=False, blank=False)
    state = models.CharField(max_length=150, null=False, blank=False)
    zipcode = models.CharField(max_length=150, null=False, blank=False)
    payment_mode = models.CharField(max_length=150, null=False)
    payment_id = models.CharField(max_length=250, null=True)
    message = models.TextField(null=True, blank=True)
    total_price = models.FloatField(default=0)
    create_at = models.DateTimeField(auto_now_add=True)
    upadte_at = models.DateTimeField(auto_now=True)
    orderstatus = (
        ('pending', 'Pending'),
        ('out of shipping ', 'Out of Shipping'),
        ('complete', 'Complete'),
    )
    status = models.CharField(
        max_length=100, choices=orderstatus, default='pending')
    tracking_no = models.CharField(max_length=150, null=False)

    def __str__(self):
        return '%s %s' % (self.id, self.tracking_no)


class OrderItem(models.Model):
    order = models.ForeignKey(Order,  on_delete=models.CASCADE)
    product = models.ForeignKey(Product,  on_delete=models.CASCADE)
    price = models.FloatField(null=False, blank=False)
    quantity = models.PositiveIntegerField(null=False, blank=False)

    def __str__(self):
        return '%s %s' % (self.id, self.order.tracking_no)

carts/views.py
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import redirect, render
from .basket import Basket


import random
from django.contrib.auth import get_user_model
from .models import Order, OrderItem
from django.contrib.auth.decorators import login_required

# Create your views here.
from profiles.models import Profile
from stores.models import Product

user = get_user_model()


def cart_view(request):
    return render(request, 'carts/cart_view.html')


def cart_add_product(request):
    cart = Basket(request)
    if request.method == 'POST':
        prod = int(request.POST['product_id'])
        product = Product.objects.get(id=prod)
        cart.add_to_cart(product=product, qty=1)
        cart_qty_total = cart.__len__()
    return JsonResponse({'status': 'added to basket successfully', 'cart_qty_total': cart_qty_total})


def cart_add_product_from_detail(request):
    cart = Basket(request)
    if request.method == 'POST':
        pro_id = int(request.POST['product_id'])
        pro_qty = int(request.POST['product_qty'])
        product = Product.objects.get(id=pro_id)

        if product.product_quantity >= pro_qty > 0:
            cart.add_to_cart_mulitply(product=product, qty=pro_qty)
            response = 'updated Quantity of basket successfully'
            cart_qty_total = cart.__len__()
        else:
            response = 'This Quantity Out Of Stock'
    return JsonResponse({'status': response, 'cart_qty_total': cart_qty_total})


def update_cart(request):
    cart = Basket(request)
    if request.method == 'POST':
        pro_id = int(request.POST['product_id'])
        pro_qty = int(request.POST['product_qty'])
        product = Product.objects.get(id=pro_id)

        if product.product_quantity >= pro_qty > 0:
            cart.add_to_cart_mulitply(product=product, qty=pro_qty)
            response = 'updated Quantity of basket successfully'
            cart_qty_total = cart.__len__()
        else:
            cart.delete_product(product=product)
            response = 'removed from basket successfully'
            cart_qty_total = cart.__len__()

    return JsonResponse({'status': response, 'cart_qty_total': cart_qty_total})


def delete_cart_item(request):
    cart = Basket(request)
    if request.method == 'POST':
        pro_id = int(request.POST['product_id'])
        product = Product.objects.get(id=pro_id)
        cart.delete_product(product=product)
        cart_qty_total = cart.__len__()
        response = 'Removed Product of basket successfully'
    return JsonResponse({'status': response, 'cart_qty_total': cart_qty_total})


@login_required(login_url='users:account_login')
def checkout_cart(request):
    cart = Basket(request)

    if request.method == 'POST':
        current_user = user.objects.filter(id=request.user.id).first()
        if not current_user.first_name:
            current_user.first_name = request.POST['fname']
            current_user.last_name = request.POST['lname']
            current_user.save()
        if not Profile.objects.filter(user=current_user):
            profile = Profile()
            profile.email = request.POST['email']
            profile.phone = request.POST['phone']
            profile.address = request.POST['address']
            profile.adress2 = request.POST['adress2']
            profile.state = request.POST['state']
            profile.city = request.POST['city']
            profile.zipcode = request.POST['zipcode']
            profile.save()
        neworder = Order()
        neworder.user_id = request.user.id
        neworder.email = request.POST['email']
        neworder.phone = request.POST['phone']
        neworder.address = request.POST['address']
        neworder.address2 = request.POST['address2']
        neworder.state = request.POST['state']
        neworder.city = request.POST['city']
        neworder.zipcode = request.POST['zipcode']
        neworder.payment_mode = request.POST['payment_mode']
        track_no = 'site' + str(random.randint(1111111, 9999999))
        while Order.objects.filter(tracking_no=track_no) is None:
            track_no = 'site' + str(random.randint(1111111, 9999999))
        neworder.tracking_no = track_no
        total = 0
        for item in cart:
            total = total + item['total_sub_price']
        if cart.__len__() > 0:
            neworder.total_price = total
            neworder.save()
            for item in cart:
                OrderItem.objects.create(
                    order=neworder,
                    product=item['product'],
                    price=item['price'],
                    quantity=item['qty']
                )
                order_product = Product.objects.filter(name=item['product']).first()
                order_product.product_quantity = order_product.product_quantity - item['qty']
                order_product.save()
            cart.clear_cart()
            messages.success(request, 'order placed')
        else:
            messages.success(request, 'cart is empty')
    return redirect('/')


@login_required(login_url='users:account_login')
def place_order_cart(request):
    user = request.user
    profile = Profile.objects.get(user=user)
    context = {'profile': profile, 'user': user}
    return render(request, 'carts/placeorder.html', context)

carts/templates/carts/cart_view.html
{% extends '_base.html' %}
{% load static %}
{% block carousel %}
<style>
  .img-shope {
    width: 432px;
    height: 432px;
  }
</style>
{% include 'includes/navbar.html' %}
<!-- Page Header Start -->
<div class="container-fluid bg-secondary mb-5">
  <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
    <h1 class="font-weight-semi-bold text-uppercase mb-3">Your Cart</h1>
    <div class="d-inline-flex">
      <p class="m-0"><a href="{% url 'stores:store_home' %}">Home</a></p>
      <p class="m-0 px-2">-</p>
      <p class="m-0">Shopping Cart</p>
    </div>
  </div>
</div>
<!-- Page Header End -->

<!-- Cart Start -->
<div class="container-fluid pt-5">
  <div class="row px-xl-5">
    <div class="col-lg-8 table-responsive mb-5 product-reload">
      <table class="table table-bordered text-center mb-0">
        <thead class="bg-secondary text-dark">
          <tr>
            <th>Image</th>
            <th>Products</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total</th>
            <th>Remove</th>
          </tr>
        </thead>
        <tbody class="align-middle ">
          {% for item in cart %}
          {% with product=item.product %}
          <tr class='product-data' data-index={{product.id}}>
            <form action="" method="post">
            <td class="align-middle">
              <img src="{{product.product_image.url}}" alt="" style="width: 50px;height:50px;"> 
            </td>
            <td class="align-middle">
              {{product.name|capfirst}}
            </td>
            <td class="align-middle">${{item.price}}</td>
            <td class="align-middle">
              {% csrf_token %}
              <input type="hidden" name=""class='product-id' value={{product.id}}>
              <div class="input-group quantity mx-auto" style="width: 100px;">
                <div class="input-group-btn">
                  <button type="submit" class="btn btn-sm btn-primary btn-minus update-cart-qty">
                    <i class="fa fa-minus"></i>
                  </button>
                </div>
                <input type="text" class="form-control form-control-sm bg-secondary text-center update-qty-cart" value={{item.qty}}>
                <div class="input-group-btn">
                  <button  type="submit" class="btn btn-sm btn-primary btn-plus update-cart-qty">
                    <i class="fa fa-plus"></i>
                  </button>
                </div>
              </div>
            </td>
            <td class="align-middle">${{item.total_sub_price}}</td>
            <td class="align-middle">
              <button class="btn btn-sm btn-primary remove-cart-item">
                <i class="fa fa-times"></i></button></td>
            </form>
          </tr>
          {% endwith %}
          {% empty %}
          <h3>Your Cart is Empty</h3>
          <hr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="col-lg-4">
      <form class="mb-5" action="">
        <div class="input-group">
          <input type="text" class="form-control p-4" placeholder="Coupon Code">
          <div class="input-group-append">
            <button class="btn btn-primary">Apply Coupon</button>
          </div>
        </div>
      </form>
      <div class="card border-secondary mb-5">
        <div class="card-header bg-secondary border-0">
          <h4 class="font-weight-semi-bold m-0">Cart Summary</h4>
        </div>
        <div class="card-body cart-total-price">
          <div class="d-flex justify-content-between mb-3 pt-1">
            <h6 class="font-weight-medium">Subtotal</h6>
            <h6 class="font-weight-medium ">${{cart.total_price}}</h6>
          </div>
          <div class="d-flex justify-content-between">
            <h6 class="font-weight-medium">Shipping</h6>
            <h6 class="font-weight-medium">$10</h6>
          </div>
        </div>
        <div class="card-footer border-secondary bg-transparent">
          <div class="d-flex justify-content-between mt-2">
            <h5 class="font-weight-bold">Total</h5>
            <h5 class="font-weight-bold">$160</h5>
          </div>
          <a href="{% url 'carts:place_order_cart' %}" class="btn btn-block btn-primary my-3 py-3">Proceed To Checkout</a>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Cart End -->
<script src="{% static 'js/cart.js' %}"></script>
{% endblock carousel %}

carts/templates/carts/placeorder.html
{% extends '_base.html' %}
{% load static %}
{% block carousel %}
<meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval' http://www.google.com">

<style>
  .img-shope {
    width: 432px;
    height: 432px;
  }
  table > tr > td {
      font-size:16px;
      font-weight:400 !important;
  }
</style>
{% include 'includes/navbar.html' %}
    <!-- Page Header Start -->
    <div class="container-fluid bg-secondary mb-5">
        <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
            <h1 class="font-weight-semi-bold text-uppercase mb-3">Checkout</h1>
            <div class="d-inline-flex">
                <p class="m-0"><a href="{% url 'stores:store_home' %}">Home</a></p>
                <p class="m-0 px-2">-</p>
                <p class="m-0">Checkout</p>
            </div>
        </div>
    </div>
    <!-- Page Header End -->


    <!-- Checkout Start -->
    <div class="container-fluid pt-5">
        <div class="row px-xl-5">
            <div class="col-lg-8">
                <form action="{% url 'carts:checkout_cart' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                <div class="mb-4">
                    <h4 class="font-weight-semi-bold mb-4">Billing Address</h4>
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label>First Name</label>
                            <input class="form-control" type="text" value="{{user.first_name}}" name="fname">
                        </div>
                        <div class="col-md-6 form-group">
                            <label>Last Name</label>
                            <input class="form-control" type="text" value="{{user.last_name}}" name="lname">
                        </div>
                        <div class="col-md-6 form-group">
                            <label>E-mail</label>
                            <input class="form-control" type="text"value="{{user.email}}" name="email">
                        </div>
                        <div class="col-md-6 form-group">
                            <label>Mobile No</label>
                            <input class="form-control" type="text" value="{{profile.phone}}" name="phone">
                        </div>
                        <div class="col-md-6 form-group">
                            <label>Address Line 1</label>
                            <input class="form-control" type="text" value="{{profile.address}}" name="address">
                        </div>
                        <div class="col-md-6 form-group">
                            <label>Address Line 2</label>
                            <input class="form-control" type="text" value="{{profile.address2}}" name="address2">
                        </div>
                        <div class="col-md-6 form-group">
                            <label>City</label>
                            <input class="form-control" type="text"value="{{profile.city}}" name="city">
                        </div>
                        <div class="col-md-6 form-group">
                            <label>State</label>
                            <input class="form-control" type="text" value="{{profile.state}}" name="state">
                        </div>
                        <div class="col-md-6 form-group">
                            <label>ZIP Code</label>
                            <input class="form-control" type="text" value="{{profile.zipcode}}" name="zipcode">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="card border-secondary mb-5">
                    <div class="card-header bg-secondary border-0">
                        <h4 class="font-weight-semi-bold m-0">Order Total</h4>
                    </div>
                    <div class="card-body">
                        <table class="table">
                            <thead>
                                <tr>  
                                <th scope="col">Product</th>
                                <th scope="col">Qty</th>
                                <th scope="col">SubTotal</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in cart %}
                                <tr>
                                <td>{{item.product.name}}</td>
                                <td>{{item.qty}}</td>
                                <td>${{item.total_sub_price}}</td>
                                </tr>
                                {% endfor %}
                            </tbody> 
                        </table>                   
                        <hr class="mt-0">
                        <div class="d-flex justify-content-between mb-3 pt-1">
                            <h6 class="font-weight-medium">Subtotal</h6>
                            <h6 class="font-weight-medium totalprice">${{cart.total_price}}</h6>
                        </div>
                        <div class="d-flex justify-content-between">
                            <h6 class="font-weight-medium">Shipping</h6>
                            <h6 class="font-weight-medium">$10</h6>
                        </div>
                    </div>
                    <div class="card-footer border-secondary bg-transparent">
                        <div class="d-flex justify-content-between mt-2">
                            <h5 class="font-weight-bold">Total</h5>
                            <h5 class="font-weight-bold">$160</h5>
                        </div>
                    </div>
                </div>
                <div class="card border-secondary mb-5">
                    <div class="card-header bg-secondary border-0">

                        <h4 class="font-weight-semi-bold m-0">Payment</h4>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                        <div class="form-group">
                            <div class="custom-control custom-radio">
                                <input type="hidden" class="custom-control-input" value='paypal' name="payment_mode">
                                <div id="paypal-button-container"></div>
                            </div>
                        </div>
                        <div class="">
                            <div class="custom-control custom-radio">
                                <input type="radio" class="custom-control-input" name="payment" id="banktransfer">
                                <label class="custom-control-label" for="banktransfer">Bank Transfer</label>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer border-secondary bg-transparent">
                        <button type="submit" class="btn btn-lg btn-block btn-primary font-weight-bold my-3 py-3 placedorder">Place Order</a>
                    </div>
                </div>
            </form>
            </div>
        </div>
    </div>
    <!-- Checkout End -->

    <script src="https://www.paypal.com/sdk/js?client-id=Ac4tStwHC8ANuMMwYUSzV9G6lV1Q1RCgEzQv7ETpuDxtAJe621pq4n_qJ7n3u7aCrS9RlqMqGWcNKUk-&currency=USD"></script>
 
     <script>

      paypal.Buttons({

        // Sets up the transaction when a payment button is clicked

        createOrder: (data, actions) => {

          return actions.order.create({

            purchase_units: [{

              amount: {

                value:'0.1' //'{{cart.total_price}}' // Can also reference a variable or function

              }

            }]

          });

        },

        // Finalize the transaction after payer approval

        onApprove: (data, actions) => {

          return actions.order.capture().then(function(orderData) {

            // Successful capture! For dev/demo purposes:

            console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));

            const transaction = orderData.purchase_units[0].payments.captures[0];

            alert(`Transaction ${transaction.status}: ${transaction.id}\n\nSee console for all available details`);

            // When ready to go live, remove the alert and show a success message within this page. For example:

            // const element = document.getElementById('paypal-button-container');

            // element.innerHTML = '<h3>Thank you for your payment!</h3>';

            // Or go to another URL:  actions.redirect('thank_you.html');

          });

        }

      }).render('#paypal-button-container');

    </script>
{% endblock carousel %}