core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('',include('stores.urls',namespace='stores')),
    path('account/',include('users.urls',namespace='users')),
    path('profile/',include('profiles.urls',namespace='profiles')),
    path('carts/',include('carts.urls',namespace='carts')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

stores/urls.py
from django.urls import path
from . import views

app_name = 'stores'
urlpatterns = [
    path('',views.store_home,name='store_home'),
    path('shopping/', views.store_shopping, name='store_shopping'),
    path('shopping/<slug:slug_cate>/', views.store_category_product,name='store_category_product'),
    path('product/<slug:pro_slug>/', views.store_product_details,name='product_detail'),
    path('product/sub/<slug:cat_slug>/',views.store_sub_menu_product, name='store_sub_menu_product'),
    path('search/', views.product_search, name='product_search')
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from . import views

app_name = 'users'

urlpatterns = [
    path('register/',views.account_register,name='account_register'),
    path('activate-account/<uidb64>/<token>/',views.account_activte,name='activate'),
    path('login/',views.account_login,name='account_login'),
    path('logout/',views.account_logout,name='account_logout'),

    # reset password
    path('password_reset/',auth_view.PasswordResetView.as_view(
                                                                template_name='users/reset/password_reset.html',
                                                                email_template_name='users/reset/email_reset.html',
                                                                success_url='/account/password_reset_done'),
                                                                name='password_reset'),
    path('password_reset_done/',auth_view.PasswordResetDoneView.as_view(
                                                                        template_name='users/reset/password_reset_done.html'),
                                                                        name='password_reset_done'),

    path('password_reset_confirm/<uidb64>/<token>/',auth_view.PasswordResetConfirmView.as_view(
                                                                    template_name='users/reset/password_reset_confirm.html',
                                                                    success_url='/account/password_reset_complete'),name='password_reset_confirm'),
    path('password_reset_complete/',auth_view.PasswordResetCompleteView.as_view(template_name='users/reset/password_reset_complete.html'),
                                                                                name='password_reset_complete'),                                                                                                                          
    path('user_contact/', views.users_contact, name='users_contact'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager


# Create your models here.
class CustomManager(BaseUserManager):
    def create_superuser(self, username, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('is satff must be True')

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('is superuser must be True')

        if extra_fields.get('is_active') is not True:
            raise ValueError('is active must be True')

        user = self.create_user(username, email, password, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_user(self, username, email, password, **extra_fields):
        email = self.normalize_email(email)
        if not email:
            raise ValueError('email is required')
        user = self.model(username=username, email=email,
                          password=password, **extra_fields)
        user.set_password(password)
        user.save()
        return user


class CustomUser(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(max_length=100, null=True, blank=True)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    username = models.CharField(max_length=200, unique=True,
                                help_text='username must be unique', blank=False, null=False)
    email = models.CharField(max_length=200, unique=True,
                             help_text='email must be unique', blank=False, null=False)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    objects = CustomManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', ]

    def __str__(self):
        return self.username


class TakeMessage(models.Model):
    name = models.CharField(max_length=150, null=False, blank=False)
    email = models.EmailField(max_length=150, null=False, blank=False)
    subject = models.CharField(max_length=200, null=False, blank=False)
    message_body = models.TextField(null=False, blank=False)
    send_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.email} == {self.send_at}'

users/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()

class RegisterForm(UserCreationForm):
    username = forms.CharField(label="Username", widget=forms.TextInput(
        attrs={'class': 'form-control', 'id': 'username', 'placeholder':"Your Name"}))
    email = forms.CharField(label="Email", widget=forms.EmailInput(
        attrs={'class': 'form-control', 'id': 'email', 'placeholder': "Your Email"}))
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'id': 'subject', 'placeholder': "Your Password"}))
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'id': 'message', 'placeholder': "Confirm Your Password"}))

    class Meta:
        model = User
        fields = ['username','email','password1','password2']


class LoginForm(forms.Form):
    email = forms.EmailField(label='Email', widget=forms.EmailInput(
        attrs={'class': 'form-control', 'id': 'name', 'placeholder': "Your Name"}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'id': 'subject', 'placeholder': "Your Password"}))

users/views.py
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.conf import settings
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.core.mail import EmailMessage,send_mail
from .token import generate_token
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth import login, logout, authenticate
from .forms import RegisterForm, LoginForm
from .models import TakeMessage
# Create your views here.


def send_email_user(user, request):
    subject = 'activate email'
    current_site = get_current_site(request)
    body = render_to_string('users/active_account.html', {
        'user': user,
        'domain': current_site.domain,
        'uid': force_str(urlsafe_base64_encode(force_bytes(user.pk))),
        'token': generate_token.make_token(user)
    })
    email = EmailMessage(
        subject=subject,
        body=body,
        from_email=settings.FROM_USER_EMAIL,
        to=[user.email, ]
    )
    email.send()


def account_register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            n_f = form.save(commit=False)
            n_f.username = form.cleaned_data.get('username')
            n_f.email = form.cleaned_data.get('email')
            n_f.set_password(form.cleaned_data.get('password1'))
            form.save()
            send_email_user(n_f, request)
            messages.success(request, 'Please Check Your Email Address ')
            return redirect('/')

    else:
        form = RegisterForm()

    context = {
        'form': form,
    }
    return render(request, 'users/register.html', context)


def account_activte(request, uidb64, token):
    try:
        user_id = urlsafe_base64_decode(force_str(uidb64))
        user = get_user_model().objects.get(id=user_id)
        if user is not None and generate_token.check_token(user, token):
            user.is_active = True
            user.save()
            messages.success(
                request, 'your account has been activated successfully')
            login(request, user)
            return redirect('/')
    except:
        messages.error(request, 'please try again later')

    return render(request, 'users/errors_activate.html')


def account_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            user = authenticate(email=email, password=password)
            if user:
                login(request, user)
                messages.success(request, 'welcom ' + user.username + ' back')
                return redirect('/')
    else:
        form = LoginForm()
    context = {
        'form': form
    }
    return render(request, 'users/login.html', context)


def account_logout(request):
    logout(request)
    messages.success(request, 'You Logged out Successfully ')
    return redirect('/')


def users_contact(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')
        if name and email and subject and message:
            send_mail(subject, message,email,[settings.FROM_USER_EMAIL,])
            TakeMessage.objects.create(
                name=name, email=email, subject=subject, message_body=message)
            messages.success(request,'We Get Your Contact , Thank You')
            return redirect('/')

        else:
            messages.success(request, 'Sorry , Something is Going Wrong')
    return render(request,'users/contact.html')

users/templates/users/active_account.html
{% autoescape off %}
Hi : {{user}}
 Please click on the link to confirm your registration,
        
 http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}
        
{% endautoescape %}

users/templates/users/contact.html
{% extends '_base.html' %}
{% block carousel %}
<style>
    .img-shope{
        width: 432px;
        height:432px;
    }
</style>
{% include 'includes/navbar.html' %}
      <!-- Page Header Start -->
    <div class="container-fluid bg-secondary mb-5">
        <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
            <h1 class="font-weight-semi-bold text-uppercase mb-3">Contact Us</h1>
            <div class="d-inline-flex">
                <p class="m-0"><a href="{% url 'stores:store_home' %}">Home</a></p>
                <p class="m-0 px-2">-</p>
                <p class="m-0">Contact</p>
            </div>
        </div>
    </div>
    <!-- Page Header End -->


    <!-- Contact Start -->
    
    <div class="container-fluid ">
        <div class="text-center mb-4">
            <h2 class="section-title px-5 border-bottom"><span class="px-2">Contact For Any Queries</span></h2>
        
        </div>
        
        <div class="row px-xl-5">
            <div class="col-lg-7 mb-5">
                <div class="contact-form">
                    <div id="success"></div>
                    <form name="sentMessage" method='post'>
                        {% csrf_token %}
                        <div class="control-group">
                            <input type="text" class="form-control" name="name" id="name" placeholder="Your Name"
                                required="required" data-validation-required-message="Please enter your name" />
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group">
                            <input type="email" class="form-control" name="email" id="email" placeholder="Your Email"
                                required="required" data-validation-required-message="Please enter your email" />
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group">
                            <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject"
                                required="required" data-validation-required-message="Please enter a subject" />
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group">
                            <textarea class="form-control" rows="6" name="message" id="message" placeholder="Message"
                                required="required"
                                data-validation-required-message="Please enter your message"></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                        <div>
                            <button class="btn btn-primary py-2 px-4" type="submit" >Send
                                Message</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-lg-5 mb-5">
                <h5 class="font-weight-semi-bold mb-3">Get In Touch</h5>
                <p>Justo sed diam ut sed amet duo amet lorem amet stet sea ipsum, sed duo amet et. Est elitr dolor elitr erat sit sit. Dolor diam et erat clita ipsum justo sed.</p>
                <div class="d-flex flex-column mb-3">
                    <h5 class="font-weight-semi-bold mb-3">Store 1</h5>
                    <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
                    <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                    <p class="mb-2"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
                </div>
                <div class="d-flex flex-column">
                    <h5 class="font-weight-semi-bold mb-3">Store 2</h5>
                    <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
                    <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                    <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->

{% endblock carousel %}

users/templates/users/errors_activate.html
<h1> Error Activate </h1>
<p>Try again later </p>

users/templates/users/login.html
{% extends '../_base.html' %}
{% block topsearch %}{% endblock topsearch %}
{% block carousel %}{% endblock carousel %}
{% block contect %}

<!-- Contact Start -->
   <div class="container-fluid">
   {% include 'includes/navbar.html' %}
   <div class="border-bottom"></div>
   </div> 
<div class="container-fluid mt-4">
 
    <div class="text-center mb-4">
        <h2 class="section-title px-5"><span class="px-2">Login Now</span></h2>
    </div>
    <div class="row px-xl-5">
        <div class="col-lg-7 mb-5">
            <div class="contact-form">
                <form method='post'>
                    {% csrf_token %}
                    <div class="control-group">
                        {{form.email.label}}
                        {{form.email}}
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="control-group">
                        {{form.password.label}}
                        {{form.password}}
                        <p class="help-block text-danger"></p>
                    </div>
                    <div>
                        <button class="btn btn-primary py-2 px-4" type="submit">Login</button>
                    </div>
                </form>
            </div>
            <span class="d-flex mt-4">
                <p>You Do Not Have an Account Yet ? </p><a class="mr-3 ml-2" href="{% url 'users:account_register' %}">
                    sign up</a><br>
            </span>
            <span class="d-flex">
                <p>Forgtten Your Password ? </p><a class="mr-3 ml-2" href="{% url 'users:password_reset' %}"> Get
                    Help</a><br>
            </span>
        </div>
        <div class="col-lg-5 mb-5">
            <h5 class="font-weight-semi-bold mb-3">Get In Touch</h5>
            <p>Justo sed diam ut sed amet duo amet lorem amet stet sea ipsum, sed duo amet et. Est elitr dolor elitr
                erat sit sit. Dolor diam et erat clita ipsum justo sed.</p>
            <div class="d-flex flex-column mb-3">
                <h5 class="font-weight-semi-bold mb-3">Store 1</h5>
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
                <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                <p class="mb-2"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
            </div>
            <div class="d-flex flex-column">
                <h5 class="font-weight-semi-bold mb-3">Store 2</h5>
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
                <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
            </div>
        </div>
    </div>
</div>
<!-- Contact End -->
{% endblock contect %}

users/templates/users/register.html
{% extends '../_base.html' %}
{% block topsearch %}{% endblock topsearch %}
{% block carousel %}{% endblock carousel %}
{% block contect %}
    <!-- Contact Start -->
   <div class="container-fluid">
   {% include 'includes/navbar.html' %}
   <div class="border-bottom"></div>
   </div> 
        <div class="text-center mb-4 mt-4">
            <h2 class="section-title px-5"><span class="px-2">Registration Now</span></h2>
        </div>
        <div class="row px-xl-5">
            <div class="col-lg-7 mb-5">
                <div class="contact-form">
                    <form method='post'>
                        {% csrf_token %}
                        <div class="control-group">
                          {{form.as_p}}
                        </div>
                       
                        <div>
                            <button class="btn btn-primary py-2 px-4" type="submit" >Create</button>
                          </div>
                    </form>
                </div>
                 <span class="d-flex mt-4">
                   <p>You Already Have an Account? </p><a class="mr-3 ml-2" href="{% url 'users:account_login' %}"> Login Now</a><br>
                </span>
            </div>
            <div class="col-lg-5 mb-5">
                <h5 class="font-weight-semi-bold mb-3">Get In Touch</h5>
                <p>Justo sed diam ut sed amet duo amet lorem amet stet sea ipsum, sed duo amet et. Est elitr dolor elitr erat sit sit. Dolor diam et erat clita ipsum justo sed.</p>
                <div class="d-flex flex-column mb-3">
                    <h5 class="font-weight-semi-bold mb-3">Store 1</h5>
                    <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
                    <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                    <p class="mb-2"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
                </div>
                <div class="d-flex flex-column">
                    <h5 class="font-weight-semi-bold mb-3">Store 2</h5>
                    <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
                    <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                    <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->
{% endblock contect %}