carts/urls.py
from django import views
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('',views.cart_view,name='cart_view'),
    path('add-to-cart/',views.cart_add_product,name='add_to_cart_one'),
    path('add-to-cart-detail/', views.cart_add_product_from_detail,
         name='cart_add_product_from_detail'),
    path('update-cart-qty/',views.update_cart,name='update_cart'),
    path('delete-cart-qty/', views.delete_cart_item, name='delete_cart_item'),
    path('placeorder/', views.place_order_cart, name='place_order_cart'),
    path('checkoutcart/', views.checkout_cart, name='checkout_cart'),
 
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('',include('stores.urls',namespace='stores')),
    path('account/',include('users.urls',namespace='users')),
    path('profile/',include('profiles.urls',namespace='profiles')),
    path('carts/',include('carts.urls',namespace='carts')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

stores/urls.py
from django.urls import path
from . import views

app_name = 'stores'
urlpatterns = [
    path('',views.store_home,name='store_home'),
    path('shopping/', views.store_shopping, name='store_shopping'),
    path('shopping/<slug:slug_cate>/', views.store_category_product,name='store_category_product'),
    path('product/<slug:pro_slug>/', views.store_product_details,name='product_detail'),
    path('product/sub/<slug:cat_slug>/',views.store_sub_menu_product, name='store_sub_menu_product'),
    path('search/', views.product_search, name='product_search')
]

templates/_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8" />
  <title>{% block title %}{% endblock title %}</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport" />
  <meta content="Shop Style dress" name="keywords" />
  <meta content="Free HTML Templates" name="description" />

  <!-- Favicon -->
  {% comment %} <link href="{% static ' img/favicon.ico' %}" rel="icon" /> {% endcomment %}

  <!-- Google Web Fonts -->
  <link rel="preconnect" href="https://fonts.gstatic.com" />
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
    rel="stylesheet" />

  <!-- Font Awesome -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet" />

  <!-- Libraries Stylesheet -->
  <link rel="stylesheet" href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %} " />

    <link rel="stylesheet" href="{% static 'css/alertify.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/default.min.css' %}"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">

  <!-- Customized Bootstrap Stylesheet -->
  <link href="{% static 'css/style.css' %} " rel="stylesheet" />
  <link href="{% static 'css/review_star.css' %} " rel="stylesheet" />
  
  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
</head>

<body>

  <!-- Topbar Start -->
  
  <div class="container-fluid">
    <div class="row bg-secondary py-2 px-xl-5">
      <div class="col-lg-6 d-none d-lg-block">
        <div class="d-inline-flex align-items-center">
          <a class="text-dark" href="">FAQs</a>
          <span class="text-muted px-2">|</span>
          <a class="text-dark" href="">Help</a>
          <span class="text-muted px-2">|</span>
          <a class="text-dark" href="">Support</a>
        </div>
      </div>
      <div class="col-lg-6 text-center text-lg-right">
        <div class="d-inline-flex align-items-center">
          <a class="text-dark px-2" href="">
            <i class="fab fa-facebook-f"></i>
          </a>
          <a class="text-dark px-2" href="">
            <i class="fab fa-twitter"></i>
          </a>
          <a class="text-dark px-2" href="">
            <i class="fab fa-linkedin-in"></i>
          </a>
          <a class="text-dark px-2" href="">
            <i class="fab fa-instagram"></i>
          </a>
          <a class="text-dark pl-2" href="">
            <i class="fab fa-youtube"></i>
          </a>
        </div>
      </div>
    </div>

{% block topsearch %}
    <div class="row align-items-center py-3 px-xl-5">
      <div class="col-lg-3 d-none d-lg-block">
        <a href="{% url 'stores:store_home' %}" class="text-decoration-none">
          <h1 class="m-0 display-5 font-weight-semi-bold">
            <span class="text-primary font-weight-bold border px-3 mr-1">E</span>Shopper
          </h1>
        </a>
      </div>
      <div class="col-lg-6 col-6 text-left">
        <form action="{% url 'stores:product_search' %}" method='get'>
          <div class="input-group">
            <input type="search" name='search_store' class="form-control" placeholder="Search for products" />
            <div class="input-group-append">
             <span class="input-group-text bg-transparent text-primary">
                <i class="fa fa-search"></i>
              </span>
            </div>
          </div>
        </form>
      </div>
      <div class="col-lg-3 col-6 text-right">
        <a href="" class="btn border">
          <i class="fas fa-heart text-primary"></i>
          <span class="badge">0</span>
        </a>
        {% with product=cart|length %}
        {% if product > 0 %}
        <a href="{% url 'carts:cart_view' %}" class="btn border">
          <i class="fas fa-shopping-cart text-primary"></i>
          <span class="badge" id='cart-qty'>{{product}}</span>
        </a>
        {% else %}
          <a href="{% url 'carts:cart_view' %}" class="btn border">
          <i class="fas fa-shopping-cart text-primary"></i>
          <span class="badge" id='cart-qty'>0</span>
        </a>
        {% endif %}
        {% endwith %}
      </div>
    </div>
  </div>
  {% endblock topsearch %}
  <!-- Topbar End -->
  <!-- Include navbar and carousel -->

  <!-- Navbar End -->


 {% block contect %}{% endblock contect %}
 
  {% block carousel %}{% endblock carousel %}


 

  <!-- end Include navbar and carousel -->


<!-- Featured Start -->
  {% block featured %}{% endblock featured %}
<!-- Featured End -->


  
<!-- Categories Start -->
  {% block category %}{% endblock category %}
<!-- Categories End -->

 
  

  {% block product_index %}
  <!-- Cproduct_index -->

  <!-- product_index End -->
  {% endblock product_index %}


 <!-- Footer Start -->
{% block footer %}
  <div class="container-fluid bg-secondary text-dark mt-5 pt-5">
    <div class="row px-xl-5 pt-5">
      <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
        <a href="" class="text-decoration-none">
          <h1 class="mb-4 display-5 font-weight-semi-bold">
            <span class="text-primary font-weight-bold border border-white px-3 mr-1">E</span>Shopper
          </h1>
        </a>
        <p>
          Dolore erat dolor sit lorem vero amet. Sed sit lorem magna, ipsum no
          sit erat lorem et magna ipsum dolore amet erat.
        </p>
        <p class="mb-2">
          <i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street,
          New York, USA
        </p>
        <p class="mb-2">
          <i class="fa fa-envelope text-primary mr-3"></i>info@example.com
        </p>
        <p class="mb-0">
          <i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890
        </p>
      </div>
      <div class="col-lg-8 col-md-12">
        <div class="row">
          <div class="col-md-4 mb-5">
            <h5 class="font-weight-bold text-dark mb-4">Quick Links</h5>
            <div class="d-flex flex-column justify-content-start">
              <a class="text-dark mb-2" href="index.html"><i class="fa fa-angle-right mr-2"></i>Home</a>
              <a class="text-dark mb-2" href="shop.html"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
              <a class="text-dark mb-2" href="detail.html"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
              <a class="text-dark mb-2" href="cart.html"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
              <a class="text-dark mb-2" href="checkout.html"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
              <a class="text-dark" href="contact.html"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
            </div>
          </div>
          <div class="col-md-4 mb-5">
            <h5 class="font-weight-bold text-dark mb-4">Quick Links</h5>
            <div class="d-flex flex-column justify-content-start">
              <a class="text-dark mb-2" href="index.html"><i class="fa fa-angle-right mr-2"></i>Home</a>
              <a class="text-dark mb-2" href="shop.html"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
              <a class="text-dark mb-2" href="detail.html"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
              <a class="text-dark mb-2" href="cart.html"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
              <a class="text-dark mb-2" href="checkout.html"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
              <a class="text-dark" href="contact.html"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
            </div>
          </div>
          <div class="col-md-4 mb-5">
            <h5 class="font-weight-bold text-dark mb-4">Newsletter</h5>
            <form action="">
              <div class="form-group">
                <input type="text" class="form-control border-0 py-4" placeholder="Your Name" required="required" />
              </div>
              <div class="form-group">
                <input type="email" class="form-control border-0 py-4" placeholder="Your Email" required="required" />
              </div>
              <div>
                <button class="btn btn-primary btn-block border-0 py-3" type="submit">
                  Subscribe Now
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <div class="row border-top border-light mx-xl-5 py-4">
      <div class="col-md-6 px-xl-0">
        <p class="mb-md-0 text-center text-md-left text-dark">
          &copy;
          <a class="text-dark font-weight-semi-bold" href="#">Your Site Name</a>. All Rights Reserved. Designed by
          <a class="text-dark font-weight-semi-bold" href="https://htmlcodex.com">HTML Codex</a>
        </p>
      </div>
      <div class="col-md-6 px-xl-0 text-center text-md-right">
        <img class="img-fluid" src="img/payments.png" alt="" />
      </div>
    </div>
  </div>
{% endblock footer %}
  <!-- Footer End -->

  <!-- Back to Top -->
  <a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>

  <!-- JavaScript Libraries -->
<!--Start of Tawk.to Script-->
{% comment %} <script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/628a7d04b0d10b6f3e737c00/1g3mfgn4n';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>

<a href="https://api.whatsapp.com/send/?phone=+201091445518&text=I%27m+interested+in+your+car+for+sale&app_absent=0" target="_blank">
  <img src="{% static 'img/whatsapp.png' %}" alt="" width=100px>
</a>
<!--End of Tawk.to Script--> {% endcomment %}
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'lib/easing/easing.min.js' %}"></script>
  <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

  <!-- Contact Javascript File -->
  <script src="{% static 'mail/jqBootstrapValidation.min.js' %}"></script>
  <script src="{% static 'mail/contact.js' %}"></script>
  <script src="{% static 'js/all.min.js' %}"></script>
  <!-- Template Javascript -->
  <script src="{% static 'js/main.js' %}"></script>
  {% block javascript %}{% endblock javascript %}
  <script src="{% static 'js/alertify.min.js' %}"></script>
  <script>
        alertify.set('notifier','position', 'top-right');
        {% for msg in messages %}
        alertify.success('{{msg}}');
        {% endfor %}
  </script>
</body>

</html>